site_name: Grid
site_url: https://ggshor.github.io/Grid
repo_name: GGshor/Grid
repo_url: https://github.com/GGshor/Grid

theme:
  icon:
    logo: material/database
    repo: fontawesome/brands/git-alt
  name: material
  favicon: images/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
