title = "Grid"  # From Git
gitRepoUrl = "https://github.com/GGshor/Grid" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = [
    "Server",
    "Client",
    "Shared"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2024 GGshor. Built with Moonwave and Docusaurus"